kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odf-snapshot-controller-leaderelection
  namespace: openshift-storage
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
