kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odf-snapshot-controller-role
subjects:
  - kind: ServiceAccount
    name: odf-snapshot-controller
    namespace: openshift-storage
roleRef:
  kind: ClusterRole
  name: odf-snapshot-controller-runner
  apiGroup: rbac.authorization.k8s.io
