---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-snapshotter
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odf-external-snapshotter-runner
rules:
  - apiGroups: ["groupsnapshot.storage.openshift.io"]
    resources: ["volumegroupsnapshotclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["groupsnapshot.storage.openshift.io"]
    resources: ["volumegroupsnapshotcontents"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["groupsnapshot.storage.openshift.io"]
    resources: ["volumegroupsnapshotcontents/status"]
    verbs: ["update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odf-csi-snapshotter-role
subjects:
  - kind: ServiceAccount
    name: csi-snapshotter
roleRef:
  kind: ClusterRole
  name: odf-external-snapshotter-runner
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odf-external-snapshotter-leaderelection
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odf-external-snapshotter-leaderelection
subjects:
  - kind: ServiceAccount
    name: csi-snapshotter
roleRef:
  kind: Role
  name: odf-external-snapshotter-leaderelection
  apiGroup: rbac.authorization.k8s.io
